# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('title', models.TextField(max_length=100)),
                ('copyright', models.TextField(max_length=100)),
                ('explanation', models.TextField(max_length=7000)),
                ('hdurl', models.TextField(max_length=1500)),
                ('url', models.TextField(max_length=1500)),
                ('media_type', models.TextField(max_length=15)),
                ('service_ver', models.TextField(max_length=15)),
            ],
        ),
    ]
